apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tssc-app1-svc 
  description: Secure Supply Chain Example for Python is an interpreted,  object-oriented, high-level programming language with dynamic semantics. This sample demonstrates software supply chain security functionalty using an advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures, attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=tssc-app1-svc
    backstage.io/kubernetes-id: tssc-app1-svc 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tssc-app1-svc
    quay.io/repository-slug: opdev-tssc-demo/tssc-app1-img
  tags: ["python", "pip", "flask", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 